---
image: alpine:latest

stages:
  - preflight
  - pages

# Generic preflight template
.preflight: &preflight
  stage: preflight
  tags:
    - preflight

# Preflight jobs
yamllint:
  <<: *preflight
  image: sdesbure/yamllint
  before_script:
    - yamllint --version
  script:
    - yamllint .

jsonlint:
  <<: *preflight
  image: sahsu/docker-jsonlint
  before_script:
    - jsonlint --version || true
  script:
    - |
      for file in $(find . -type f -name "*.json"); do
        if ! jsonlint -q $file; then
          export FAILED=1
        else
          echo "$file OK"
        fi
      done
      if [ "${FAILED}" = "1" ]; then
        exit 1
      fi

markdownlint:
  <<: *preflight
  image:
    name: ruby:alpine
    entrypoint: [""]
  before_script:
    - gem install mdl
    - mdl --version
  script:
    - mdl --style all --warnings .

# Pages jobs
mkdocs:
  stage: pages
  image: python:3.7.0-alpine3.8
  script:
    - rm -f ~/.gitconfig && rm -Rf  ~/.ssh
    - apk add --no-cache git=2.18.0-r0 git-fast-import=2.18.0-r0 openssh-client=7.7_p1-r2 bash=4.4.19-r1
    - eval $(ssh-agent -s)
    - mkdir -p ~/.ssh
    - echo "$GIT_SSH_PUB_KEY" > ~/.ssh/id_rsa.pub
    - echo "$GIT_SSH_PRIV_KEY" | ssh-add -
    - ssh-keyscan github.com >> ~/.ssh/known_hosts
    - git config --global user.email "$GIT_EMAIL"
    - git config --global user.name "Git"
    - git clone $GITHUB_URL git-src/ && cd git-src/
    - git status
    - python --version
    - pip --version
    - pip install mkdocs mkdocs-material
    - 'mkdocs gh-deploy -v -c -m ":books: update docs"'
  only:
    - master
  tags:
    - pages
