---
include: https://raw.githubusercontent.com/timmo001/organization/master/gitlab-ci/js.yml

variables:
  GITHUB_REPO: "timmo001/timmo001.github.io"
  SLUG: "timmo001.github.io"
  TARGET: "."

  AARCH64: "false"
  AMD64: "false"
  ARMHF: "false"
  ARMV7: "false"
  I386: "false"

  LEGACY_TAGS: "false"

  PREFLIGHT_HADOLINT: "false"
  PREFLIGHT_JSONLINT: "false"
  PREFLIGHT_MARKDOWNLINT: "true"
  PREFLIGHT_SHELLCHECK: "false"
  PREFLIGHT_YAMLLINT: "false"
  PREFLIGHT_ESLINT: "false"
  PREFLIGHT_STYLELINT: "false"
  TEST: "false"
  DEPLOY_DOCKER: "false"
  PAGES_MKDOCS: "true"
  SNYK_DOCKER: "false"
  SNYK_YARN: "false"


mkdocs:
  stage: pages
  image: python:3.7.0-alpine3.8
  dependencies: []
  script:
    - rm -f ~/.gitconfig && rm -Rf  ~/.ssh
    - apk add --no-cache git=2.18.1-r0 git-fast-import=2.18.1-r0 openssh-client=7.7_p1-r3 bash=4.4.19-r1
    - eval $(ssh-agent -s)
    - mkdir -p ~/.ssh
    - echo "$GIT_SSH_PUB_KEY" > ~/.ssh/id_rsa.pub
    - echo "$GIT_SSH_PRIV_KEY" | ssh-add -
    - ssh-keyscan github.com >> ~/.ssh/known_hosts
    - git config --global user.email "$GIT_EMAIL"
    - git config --global user.name "Git"
    - git clone $GITHUB_URL git-src/ && cd git-src/
    - git status
    - python --version
    - pip --version
    - pip install mkdocs mkdocs-material
    - 'mkdocs gh-deploy -v -c -m ":books: update docs"'
  only:
    refs:
      - source
    variables:
      - $PAGES_MKDOCS == "true"
  tags:
    - pages
