---
include: https://raw.githubusercontent.com/timmo001/organization/master/gitlab-ci/js.yml

variables:
  GITHUB_REPO: "timmo001/timmo001.github.io"
  SLUG: "timmo001.github.io"
  TARGET: "."

  AARCH64: "false"
  AMD64: "false"
  ARMHF: "false"
  ARMV7: "false"
  I386: "false"

  LEGACY_TAGS: "false"

  PREFLIGHT_HADOLINT: "true"
  PREFLIGHT_JSONLINT: "true"
  PREFLIGHT_MARKDOWNLINT: "true"
  PREFLIGHT_SHELLCHECK: "false"
  PREFLIGHT_YAMLLINT: "false"
  PREFLIGHT_ESLINT: "false"
  PREFLIGHT_STYLELINT: "false"
  TEST: "false"
  DEPLOY_DOCKER: "false"
  PAGES_MKDOCS: "true"
  SNYK_DOCKER: "false"
  SNYK_YARN: "false"
