site_name: Timmo
site_description: Timmo's GitHub Pages
site_author: Timmo
site_url: https://git.timmo.xyz/

# Repository
repo_name: timmo001
repo_url: https://github.com/timmo001

# Copyright
copyright: 'Copyright &copy; Timmo'

# Configuration
theme:
  name: 'material'
  language: 'en'
  palette:
    primary: 'blue grey'
    accent: 'light blue'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'
  favicon: 'resources/favicon.ico'
  logo: 'resources/logo.svg'

# Customization
extra:
  search:
    language: 'en'
    tokenizer: '[\s\-\.]+'
  social:
    - type: 'github'
      link: 'https://github.com/timmo001'
    - type: 'twitter'
      link: 'https://twitter.com/timmo001'
    - type: 'stack-overflow'
      link: 'https://stackoverflow.com/users/1888770/timmo'

# Extensions
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

extra_css:
  - 'stylesheets/extra.css'

# Pages
pages:
  - Home: index.md
  - License: license.md
